# TCL File Generated by Component Editor 16.0
# Tue Mar 17 13:25:30 PKT 2020
# DO NOT MODIFY


# 
# Matmul "Matmul" v1.0
# saad 2020.03.17.13:25:30
# Matrix Multiplier 16bit input, 32bit output, 5x5
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module Matmul
# 
set_module_property DESCRIPTION "Matrix Multiplier 16bit input, 32bit output, 5x5"
set_module_property NAME Matmul
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR saad
set_module_property DISPLAY_NAME Matmul
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL PeStream
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file PeStream.v VERILOG PATH ../PeStream.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL PeStream
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file PeStream.v VERILOG PATH ../PeStream.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point streamA
# 
add_interface streamA avalon_streaming end
set_interface_property streamA associatedClock clock
set_interface_property streamA associatedReset reset
set_interface_property streamA dataBitsPerSymbol 8
set_interface_property streamA errorDescriptor ""
set_interface_property streamA firstSymbolInHighOrderBits true
set_interface_property streamA maxChannel 0
set_interface_property streamA readyLatency 0
set_interface_property streamA ENABLED true
set_interface_property streamA EXPORT_OF ""
set_interface_property streamA PORT_NAME_MAP ""
set_interface_property streamA CMSIS_SVD_VARIABLES ""
set_interface_property streamA SVD_ADDRESS_GROUP ""

add_interface_port streamA streamA_payload data Input 16
add_interface_port streamA streamA_ready ready Output 1
add_interface_port streamA streamA_valid valid Input 1


# 
# connection point streamB
# 
add_interface streamB avalon_streaming end
set_interface_property streamB associatedClock clock
set_interface_property streamB associatedReset reset
set_interface_property streamB dataBitsPerSymbol 8
set_interface_property streamB errorDescriptor ""
set_interface_property streamB firstSymbolInHighOrderBits true
set_interface_property streamB maxChannel 0
set_interface_property streamB readyLatency 0
set_interface_property streamB ENABLED true
set_interface_property streamB EXPORT_OF ""
set_interface_property streamB PORT_NAME_MAP ""
set_interface_property streamB CMSIS_SVD_VARIABLES ""
set_interface_property streamB SVD_ADDRESS_GROUP ""

add_interface_port streamB streamB_payload data Input 16
add_interface_port streamB streamB_ready ready Output 1
add_interface_port streamB streamB_valid valid Input 1


# 
# connection point resultStream
# 
add_interface resultStream avalon_streaming start
set_interface_property resultStream associatedClock clock
set_interface_property resultStream associatedReset reset
set_interface_property resultStream dataBitsPerSymbol 8
set_interface_property resultStream errorDescriptor ""
set_interface_property resultStream firstSymbolInHighOrderBits true
set_interface_property resultStream maxChannel 0
set_interface_property resultStream readyLatency 0
set_interface_property resultStream ENABLED true
set_interface_property resultStream EXPORT_OF ""
set_interface_property resultStream PORT_NAME_MAP ""
set_interface_property resultStream CMSIS_SVD_VARIABLES ""
set_interface_property resultStream SVD_ADDRESS_GROUP ""

add_interface_port resultStream streamR_payload data Output 32
add_interface_port resultStream streamR_ready ready Input 1
add_interface_port resultStream streamR_valid valid Output 1

