/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2' in SOPC Builder design 'soc_system'
 * SOPC Builder design path: ../../soc_system.sopcinfo
 *
 * Generated: Tue Mar 17 17:53:22 PKT 2020
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00020820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 130000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x12
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 130000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x12
#define ALT_CPU_NAME "nios2"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00020820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 130000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x12
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x12
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_MSGDMA
#define __ALTERA_NIOS2_GEN2


/*
 * RAM configuration
 *
 */

#define ALT_MODULE_CLASS_RAM altera_avalon_onchip_memory2
#define RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define RAM_BASE 0x0
#define RAM_CONTENTS_INFO ""
#define RAM_DUAL_PORT 0
#define RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define RAM_INIT_CONTENTS_FILE "soc_system_RAM"
#define RAM_INIT_MEM_CONTENT 1
#define RAM_INSTANCE_ID "NONE"
#define RAM_IRQ -1
#define RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RAM_NAME "/dev/RAM"
#define RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define RAM_RAM_BLOCK_TYPE "AUTO"
#define RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define RAM_SINGLE_CLOCK_OP 0
#define RAM_SIZE_MULTIPLE 1
#define RAM_SIZE_VALUE 131072
#define RAM_SPAN 131072
#define RAM_TYPE "altera_avalon_onchip_memory2"
#define RAM_WRITABLE 1


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtagUART"
#define ALT_STDERR_BASE 0x21098
#define ALT_STDERR_DEV jtagUART
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtagUART"
#define ALT_STDIN_BASE 0x21098
#define ALT_STDIN_DEV jtagUART
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtagUART"
#define ALT_STDOUT_BASE 0x21098
#define ALT_STDOUT_DEV jtagUART
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "soc_system"


/*
 * feederA_DMA_csr configuration
 *
 */

#define ALT_MODULE_CLASS_feederA_DMA_csr altera_msgdma
#define FEEDERA_DMA_CSR_BASE 0x21040
#define FEEDERA_DMA_CSR_BURST_ENABLE 1
#define FEEDERA_DMA_CSR_BURST_WRAPPING_SUPPORT 0
#define FEEDERA_DMA_CSR_CHANNEL_ENABLE 0
#define FEEDERA_DMA_CSR_CHANNEL_ENABLE_DERIVED 0
#define FEEDERA_DMA_CSR_CHANNEL_WIDTH 8
#define FEEDERA_DMA_CSR_DATA_FIFO_DEPTH 32
#define FEEDERA_DMA_CSR_DATA_WIDTH 16
#define FEEDERA_DMA_CSR_DESCRIPTOR_FIFO_DEPTH 8
#define FEEDERA_DMA_CSR_DMA_MODE 1
#define FEEDERA_DMA_CSR_ENHANCED_FEATURES 0
#define FEEDERA_DMA_CSR_ERROR_ENABLE 0
#define FEEDERA_DMA_CSR_ERROR_ENABLE_DERIVED 0
#define FEEDERA_DMA_CSR_ERROR_WIDTH 8
#define FEEDERA_DMA_CSR_IRQ 31
#define FEEDERA_DMA_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define FEEDERA_DMA_CSR_MAX_BURST_COUNT 8
#define FEEDERA_DMA_CSR_MAX_BYTE 1024
#define FEEDERA_DMA_CSR_MAX_STRIDE 1
#define FEEDERA_DMA_CSR_NAME "/dev/feederA_DMA_csr"
#define FEEDERA_DMA_CSR_PACKET_ENABLE 0
#define FEEDERA_DMA_CSR_PACKET_ENABLE_DERIVED 0
#define FEEDERA_DMA_CSR_PREFETCHER_ENABLE 0
#define FEEDERA_DMA_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define FEEDERA_DMA_CSR_RESPONSE_PORT 2
#define FEEDERA_DMA_CSR_SPAN 32
#define FEEDERA_DMA_CSR_STRIDE_ENABLE 0
#define FEEDERA_DMA_CSR_STRIDE_ENABLE_DERIVED 0
#define FEEDERA_DMA_CSR_TRANSFER_TYPE "Full Word Accesses Only"
#define FEEDERA_DMA_CSR_TYPE "altera_msgdma"


/*
 * feederA_DMA_descriptor_slave configuration
 *
 */

#define ALT_MODULE_CLASS_feederA_DMA_descriptor_slave altera_msgdma
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_BASE 0x21080
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_BURST_ENABLE 1
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_BURST_WRAPPING_SUPPORT 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_CHANNEL_ENABLE 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_CHANNEL_ENABLE_DERIVED 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_CHANNEL_WIDTH 8
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_DATA_FIFO_DEPTH 32
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_DATA_WIDTH 16
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_DESCRIPTOR_FIFO_DEPTH 8
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_DMA_MODE 1
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_ENHANCED_FEATURES 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_ERROR_ENABLE 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_ERROR_ENABLE_DERIVED 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_ERROR_WIDTH 8
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_IRQ -1
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_MAX_BURST_COUNT 8
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_MAX_BYTE 1024
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_MAX_STRIDE 1
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_NAME "/dev/feederA_DMA_descriptor_slave"
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_PACKET_ENABLE 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_PACKET_ENABLE_DERIVED 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_PREFETCHER_ENABLE 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_PROGRAMMABLE_BURST_ENABLE 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_RESPONSE_PORT 2
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_SPAN 16
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_STRIDE_ENABLE 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_STRIDE_ENABLE_DERIVED 0
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_TRANSFER_TYPE "Full Word Accesses Only"
#define FEEDERA_DMA_DESCRIPTOR_SLAVE_TYPE "altera_msgdma"


/*
 * feederB_DMA_csr configuration
 *
 */

#define ALT_MODULE_CLASS_feederB_DMA_csr altera_msgdma
#define FEEDERB_DMA_CSR_BASE 0x21020
#define FEEDERB_DMA_CSR_BURST_ENABLE 1
#define FEEDERB_DMA_CSR_BURST_WRAPPING_SUPPORT 0
#define FEEDERB_DMA_CSR_CHANNEL_ENABLE 0
#define FEEDERB_DMA_CSR_CHANNEL_ENABLE_DERIVED 0
#define FEEDERB_DMA_CSR_CHANNEL_WIDTH 8
#define FEEDERB_DMA_CSR_DATA_FIFO_DEPTH 32
#define FEEDERB_DMA_CSR_DATA_WIDTH 16
#define FEEDERB_DMA_CSR_DESCRIPTOR_FIFO_DEPTH 8
#define FEEDERB_DMA_CSR_DMA_MODE 1
#define FEEDERB_DMA_CSR_ENHANCED_FEATURES 0
#define FEEDERB_DMA_CSR_ERROR_ENABLE 0
#define FEEDERB_DMA_CSR_ERROR_ENABLE_DERIVED 0
#define FEEDERB_DMA_CSR_ERROR_WIDTH 8
#define FEEDERB_DMA_CSR_IRQ 30
#define FEEDERB_DMA_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define FEEDERB_DMA_CSR_MAX_BURST_COUNT 8
#define FEEDERB_DMA_CSR_MAX_BYTE 1024
#define FEEDERB_DMA_CSR_MAX_STRIDE 1
#define FEEDERB_DMA_CSR_NAME "/dev/feederB_DMA_csr"
#define FEEDERB_DMA_CSR_PACKET_ENABLE 0
#define FEEDERB_DMA_CSR_PACKET_ENABLE_DERIVED 0
#define FEEDERB_DMA_CSR_PREFETCHER_ENABLE 0
#define FEEDERB_DMA_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define FEEDERB_DMA_CSR_RESPONSE_PORT 2
#define FEEDERB_DMA_CSR_SPAN 32
#define FEEDERB_DMA_CSR_STRIDE_ENABLE 0
#define FEEDERB_DMA_CSR_STRIDE_ENABLE_DERIVED 0
#define FEEDERB_DMA_CSR_TRANSFER_TYPE "Full Word Accesses Only"
#define FEEDERB_DMA_CSR_TYPE "altera_msgdma"


/*
 * feederB_DMA_descriptor_slave configuration
 *
 */

#define ALT_MODULE_CLASS_feederB_DMA_descriptor_slave altera_msgdma
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_BASE 0x21070
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_BURST_ENABLE 1
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_BURST_WRAPPING_SUPPORT 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_CHANNEL_ENABLE 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_CHANNEL_ENABLE_DERIVED 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_CHANNEL_WIDTH 8
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_DATA_FIFO_DEPTH 32
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_DATA_WIDTH 16
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_DESCRIPTOR_FIFO_DEPTH 8
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_DMA_MODE 1
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_ENHANCED_FEATURES 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_ERROR_ENABLE 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_ERROR_ENABLE_DERIVED 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_ERROR_WIDTH 8
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_IRQ -1
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_MAX_BURST_COUNT 8
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_MAX_BYTE 1024
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_MAX_STRIDE 1
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_NAME "/dev/feederB_DMA_descriptor_slave"
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_PACKET_ENABLE 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_PACKET_ENABLE_DERIVED 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_PREFETCHER_ENABLE 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_PROGRAMMABLE_BURST_ENABLE 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_RESPONSE_PORT 2
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_SPAN 16
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_STRIDE_ENABLE 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_STRIDE_ENABLE_DERIVED 0
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_TRANSFER_TYPE "Full Word Accesses Only"
#define FEEDERB_DMA_DESCRIPTOR_SLAVE_TYPE "altera_msgdma"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * jtagUART configuration
 *
 */

#define ALT_MODULE_CLASS_jtagUART altera_avalon_jtag_uart
#define JTAGUART_BASE 0x21098
#define JTAGUART_IRQ 0
#define JTAGUART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAGUART_NAME "/dev/jtagUART"
#define JTAGUART_READ_DEPTH 64
#define JTAGUART_READ_THRESHOLD 8
#define JTAGUART_SPAN 8
#define JTAGUART_TYPE "altera_avalon_jtag_uart"
#define JTAGUART_WRITE_DEPTH 64
#define JTAGUART_WRITE_THRESHOLD 8


/*
 * resultsDMA_csr configuration
 *
 */

#define ALT_MODULE_CLASS_resultsDMA_csr altera_msgdma
#define RESULTSDMA_CSR_BASE 0x21000
#define RESULTSDMA_CSR_BURST_ENABLE 1
#define RESULTSDMA_CSR_BURST_WRAPPING_SUPPORT 0
#define RESULTSDMA_CSR_CHANNEL_ENABLE 0
#define RESULTSDMA_CSR_CHANNEL_ENABLE_DERIVED 0
#define RESULTSDMA_CSR_CHANNEL_WIDTH 8
#define RESULTSDMA_CSR_DATA_FIFO_DEPTH 32
#define RESULTSDMA_CSR_DATA_WIDTH 32
#define RESULTSDMA_CSR_DESCRIPTOR_FIFO_DEPTH 8
#define RESULTSDMA_CSR_DMA_MODE 2
#define RESULTSDMA_CSR_ENHANCED_FEATURES 0
#define RESULTSDMA_CSR_ERROR_ENABLE 0
#define RESULTSDMA_CSR_ERROR_ENABLE_DERIVED 0
#define RESULTSDMA_CSR_ERROR_WIDTH 8
#define RESULTSDMA_CSR_IRQ 29
#define RESULTSDMA_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define RESULTSDMA_CSR_MAX_BURST_COUNT 8
#define RESULTSDMA_CSR_MAX_BYTE 1024
#define RESULTSDMA_CSR_MAX_STRIDE 1
#define RESULTSDMA_CSR_NAME "/dev/resultsDMA_csr"
#define RESULTSDMA_CSR_PACKET_ENABLE 0
#define RESULTSDMA_CSR_PACKET_ENABLE_DERIVED 0
#define RESULTSDMA_CSR_PREFETCHER_ENABLE 0
#define RESULTSDMA_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define RESULTSDMA_CSR_RESPONSE_PORT 2
#define RESULTSDMA_CSR_SPAN 32
#define RESULTSDMA_CSR_STRIDE_ENABLE 0
#define RESULTSDMA_CSR_STRIDE_ENABLE_DERIVED 0
#define RESULTSDMA_CSR_TRANSFER_TYPE "Full Word Accesses Only"
#define RESULTSDMA_CSR_TYPE "altera_msgdma"


/*
 * resultsDMA_descriptor_slave configuration
 *
 */

#define ALT_MODULE_CLASS_resultsDMA_descriptor_slave altera_msgdma
#define RESULTSDMA_DESCRIPTOR_SLAVE_BASE 0x21060
#define RESULTSDMA_DESCRIPTOR_SLAVE_BURST_ENABLE 1
#define RESULTSDMA_DESCRIPTOR_SLAVE_BURST_WRAPPING_SUPPORT 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_CHANNEL_ENABLE 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_CHANNEL_ENABLE_DERIVED 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_CHANNEL_WIDTH 8
#define RESULTSDMA_DESCRIPTOR_SLAVE_DATA_FIFO_DEPTH 32
#define RESULTSDMA_DESCRIPTOR_SLAVE_DATA_WIDTH 32
#define RESULTSDMA_DESCRIPTOR_SLAVE_DESCRIPTOR_FIFO_DEPTH 8
#define RESULTSDMA_DESCRIPTOR_SLAVE_DMA_MODE 2
#define RESULTSDMA_DESCRIPTOR_SLAVE_ENHANCED_FEATURES 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_ERROR_ENABLE 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_ERROR_ENABLE_DERIVED 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_ERROR_WIDTH 8
#define RESULTSDMA_DESCRIPTOR_SLAVE_IRQ -1
#define RESULTSDMA_DESCRIPTOR_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RESULTSDMA_DESCRIPTOR_SLAVE_MAX_BURST_COUNT 8
#define RESULTSDMA_DESCRIPTOR_SLAVE_MAX_BYTE 1024
#define RESULTSDMA_DESCRIPTOR_SLAVE_MAX_STRIDE 1
#define RESULTSDMA_DESCRIPTOR_SLAVE_NAME "/dev/resultsDMA_descriptor_slave"
#define RESULTSDMA_DESCRIPTOR_SLAVE_PACKET_ENABLE 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_PACKET_ENABLE_DERIVED 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_PREFETCHER_ENABLE 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_PROGRAMMABLE_BURST_ENABLE 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_RESPONSE_PORT 2
#define RESULTSDMA_DESCRIPTOR_SLAVE_SPAN 16
#define RESULTSDMA_DESCRIPTOR_SLAVE_STRIDE_ENABLE 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_STRIDE_ENABLE_DERIVED 0
#define RESULTSDMA_DESCRIPTOR_SLAVE_TRANSFER_TYPE "Full Word Accesses Only"
#define RESULTSDMA_DESCRIPTOR_SLAVE_TYPE "altera_msgdma"


/*
 * sysid_qsys_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_qsys_0 altera_avalon_sysid_qsys
#define SYSID_QSYS_0_BASE 0x21090
#define SYSID_QSYS_0_ID -559038737
#define SYSID_QSYS_0_IRQ -1
#define SYSID_QSYS_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_QSYS_0_NAME "/dev/sysid_qsys_0"
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_TIMESTAMP 1584448427
#define SYSID_QSYS_0_TYPE "altera_avalon_sysid_qsys"

#endif /* __SYSTEM_H_ */
